# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e22fabac3b36b52abcb4f7bb141f7a26394879cc8625fe9fcfadd2b61697e0edbd1e1227c6353eef1758b7c898940af9c0b6adb02e29a5fc6699dc60b03abcf2

test:
  secret_key_base: 0f419beb80fe6a1463e2fd1047d79bd80d9029232575bb3cd058c7cad7ed05e0aba7bdc42b0385e009c7be4fe98993c505b1e35cfa81c64d875365bea0a7bb3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
